version: '3.8'

services:
  mlflow:
    build:
      context: ./mlflow
      args:
        MLFLOW_VERSION: 2.1.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      BACKEND_STORE_URI: sqlite:////mlflow/mlflow.db
    volumes:
      - ./data:/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --serve-artifacts
      --artifacts-destination /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    restart: always