
- name: Configure Jenkins Server with Docker and Jenkins Container
  hosts: jenkins_server 
  become: yes 

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 

    - name: Install prerequisite packages for Docker and Jenkins
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - default-jdk 
          - git
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker 

    - name: Install Docker Engine, CLI, and Containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes 
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

  
    - name: Add SSH user '{{ ansible_user }}' to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      notify: Restart sshd 

    - name: Create Jenkins home directory on the host
      file:
        path: /var/jenkins_home
        state: directory
        owner: 1000 
        group: 1000 
        mode: '0755' 


    - name: Run Jenkins LTS container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk11 
        state: started
        restart_policy: unless-stopped
        ports:
          - "8081:8080" 
          - "50000:50000"
        volumes:
          - /var/jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
        user: "1000:1000"

  handlers:
      - name: Restart sshd
        service:
          name: sshd
          state: restarted