- name: Create a Compute Engine instance and Firewall Rule for Jenkins
  hosts: localhost
  tasks:
    - name: Start an instance
      google.cloud.gcp_compute_instance:
        name: jenkins-instance
        machine_type: e2-standard-2
        zone: asia-southeast1-a 
        project: mlecourse-455815 
        auth_kind: serviceaccount
        service_account_file: ../secrets/mlecourse-455815-5abd9a647f00.json 
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230727
        network_interfaces:
          - network:
              selfLink: global/networks/default
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        state: present 
      register: jenkins_vm_info

    - name: Create inbound firewall rule for Jenkins ports
      google.cloud.gcp_compute_firewall:
        name: allow-jenkins-ports 
        network:
          selfLink: global/networks/default
        allowed:
          - ip_protocol: TCP
            ports:
              - '8080' 
              - '8081' 
              - '50000' 
        source_ranges:
          - 0.0.0.0/0 
        direction: INGRESS 
        description: Allow incoming traffic on Jenkins ports 8080, 8081, 50000
        project: mlecourse-455815 
        auth_kind: serviceaccount
        service_account_file: ../secrets/mlecourse-455815-5abd9a647f00.json
        state: present