apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: model-serving
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 30000 
    protocol: TCP
    name: http
  - port: 8099 
    targetPort: 8099 
    protocol: TCP
    name: metrics 
  selector:
    app: {{ .Release.Name }}
